# Generated by Django 4.1.10 on 2023-08-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("driver", models.CharField(max_length=50)),
                ("date", models.DateField(null=True)),
                ("time", models.TimeField(null=True)),
                (
                    "label",
                    models.CharField(
                        choices=[
                            ("battery", "Battery"),
                            ("sensing ", "Sensing "),
                            ("localization", "Localization"),
                            ("planning", "Planning"),
                            ("computing node", "Computing Node"),
                            ("incident", "Incident"),
                        ],
                        default="incident",
                        max_length=30,
                    ),
                ),
                ("note", models.TextField(null=True)),
                ("stamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
