# Generated by Django 4.1.10 on 2023-08-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demoapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testlog",
            name="label",
            field=models.CharField(
                choices=[
                    ("battery", "Battery"),
                    ("sensing ", "Sensing "),
                    ("localization", "Localization"),
                    ("planning", "Planning"),
                    ("computing node", "Computing Node"),
                    ("incident", "Incident"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
